window._seedsLang = {
  'cancel': '取消',
  'ok': '确定',
  'finish': '完成',
  'submit': '提交',
  'uploaded_completed': '上传完成',
  'cannot_preview': '无法预览',
  'invalid_image_src': '图片地址无效',
  'hint_image_failed_to_load': '图片加载失败',
  'hint_only_app': '此功能仅可在外勤APP中使用',
  'hint_only_app_and_wx': '此功能仅可在微信或APP中使用',
  'hint_only_mobile': '此功能仅可在手机中使用',
  'hint_scan_failed': '扫码失败',
  'hint_try_again_later': '请稍后重试',
  'hint_max_upload': '最多只能传',
  'photos': '张照片',
  'hint_cannot_be_less_than': '不能小于',
  'hint_cannot_be_greater_than': '不能大于',
  'hint_must_number': '必须要输入数字哦',
  'hint_invalid_date': '无效的日期格式',
  'star': '颗星',
  'loading': '正在加载...',
  'hint_hideloading_after_showloading': 'showLoading后才能hideLoading',
  'hint_address_failed': '获取地址失败, 请稍后重试',
  'unit_year': '年',
  'unit_month': '月',
  'unit_date': '日',
  'unit_hour': '时',
  'unit_minute': '分',
  'unit_second': '秒',
  'unit_week': '周',
  'the': '第', // 第几周
  'copied_to_the_clipboard': '复制到剪贴板成功',
  'unable_to_access_clipboard': '当前设备不允许访问剪贴板',
  'loading': '正在刷新...',
  'no_more_data': '没有更多数据了',
  'loading_failed': '加载失败, 请稍后再试',
  'release': '释放立即刷新',
  'pull_down': '下拉可以刷新',
  'say_something': '说点什么吧...',
  'positioning': '定位中...',
  'low': '弱',
  'medium': '中',
  'strong': '强',
  'pass_in': '请传入',
  'hint_pass_in_parameters': '请传入参数',
  'hint_pass_in_correct_parameters': '请传入正确的参数',
  'wrong_parameter': '参数不正确',
  'or': '或者',
  'menu': '菜单',
  'hint_for_example_address': '例如“江苏省南京市建邺区”',
  'no_data': '暂无数据'
}
